# Generated by Django 4.2 on 2023-10-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('lastname', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
